// sdk/AuthSys-Vue-Example/src/App.vue
<template>
  <div>
    <div v-if="!initialized">
      <p>Initializing AuthSys...</p>
      <p v-if="error" style="color: red">{{ error }}</p>
    </div>
    
    <div v-else-if="sessionid">
      <h1>Welcome {{ user?.username }}!</h1>
      <button @click="logout">Logout</button>
    </div>

    <div v-else>
      <h2>Login</h2>
      <p v-if="error" style="color: red">{{ error }}</p>
      <input v-model="username" placeholder="Username" />
      <input v-model="password" type="password" placeholder="Password" />
      <button @click="handleLogin">Login</button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { useAuthSys } from './useAuthSys';

const { initialized, user, sessionid, error, init, login, logout } = useAuthSys();

const username = ref('');
const password = ref('');

onMounted(() => {
  init();
});

const handleLogin = async () => {
  await login(username.value, password.value);
};
</script>

// sdk/react/App.tsx
import React, { useEffect, useState } from 'react';
import { AuthProvider, useAuthSys } from './useAuthSys';

const LoginForm = () => {
    const { initialized, login, user, sessionid, logout } = useAuthSys();
    const [username, setUsername] = useState('');
    const [password, setPassword] = useState('');

    if (!initialized) return <div>Loading...</div>;

    if (sessionid) {
        return (
            <div>
                <h1>Welcome {user?.username}</h1>
                <button onClick={logout}>Logout</button>
            </div>
        );
    }

    return (
        <div>
            <h2>Login</h2>
            <input placeholder="Username" value={username} onChange={e => setUsername(e.target.value)} />
            <input type="password" placeholder="Password" value={password} onChange={e => setPassword(e.target.value)} />
            <button onClick={() => login(username, password)}>Login</button>
        </div>
    );
};

export default function App() {
    return (
        <AuthProvider>
            <AppInitializer />
        </AuthProvider>
    );
}

const AppInitializer = () => {
    const { init } = useAuthSys();
    useEffect(() => { init(); }, []);
    return <LoginForm />;
};
